services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    ports:
      - "52200:80"
    environment:
      DBUSER: root
      DBPASSWORD: K3#!7!pZB4C@Vfg0
      MAIL_SMTPNAME: admin@linepixer.com
      MAIL_SMTPPASSWORD: HKNuPkvyaMms
    volumes:
      - /mnt/raid/NextcloudData:/var/www/html/data
      - ./nextcloud:/var/www/html
    networks:
      default:
        ipv4_address: 10.5.0.5
  mysql:
    image: mysql:latest
    container_name: nextcloud-mysql
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_ROOT_PASSWORD: K3#!7!pZB4C@Vfg0
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "52201:3306"
    networks:
      default:
        ipv4_address: 10.5.0.6
  redis:
    image: redis:alpine
    container_name: nextcloud-redis
    ports:
      - "52202:6379"
    networks:
      default:
        ipv4_address: 10.5.0.7
networks:
  default:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
